# Generated by Django 4.1.3 on 2023-01-04 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("digital_App", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="chairman", name="User",),
        migrations.RemoveField(model_name="watchman", name="User",),
    ]
