# Generated by Django 4.1.3 on 2023-01-04 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("digital_App", "0002_remove_chairman_user_remove_watchman_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="chairman",
            name="Birthday",
            field=models.DateField(default="2022-11-20"),
        ),
        migrations.AddField(
            model_name="chairman",
            name="User",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="digital_App.user",
            ),
            preserve_default=False,
        ),
    ]
