# Generated by Django 4.1.3 on 2023-01-04 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("digital_App", "0003_chairman_birthday_chairman_user"),
    ]

    operations = [
        migrations.RemoveField(model_name="chairman", name="Birthday",),
        migrations.RemoveField(model_name="chairman", name="User",),
    ]
