# Generated by Django 4.1.3 on 2023-01-04 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("digital_App", "0004_remove_chairman_birthday_remove_chairman_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="chairman",
            name="User",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="digital_App.user",
            ),
            preserve_default=False,
        ),
    ]
