# Generated by Django 4.1.3 on 2023-01-04 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("digital_App", "0005_chairman_user"),
    ]

    operations = [
        migrations.RemoveField(model_name="chairman", name="FullName",),
        migrations.RemoveField(model_name="chairman", name="Gender",),
        migrations.RemoveField(model_name="chairman", name="Mobile",),
    ]
