# Generated by Django 4.1.3 on 2023-01-05 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "digital_App",
            "0006_remove_chairman_fullname_remove_chairman_gender_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Role_Type",
                    models.CharField(
                        blank=True,
                        choices=[("T", "Teacher"), ("S", "Student")],
                        default="",
                        max_length=5,
                    ),
                ),
            ],
            options={"db_table": "role",},
        ),
    ]
