# Generated by Django 4.1.3 on 2023-01-05 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("digital_App", "0007_role"),
    ]

    operations = [
        migrations.DeleteModel(name="Role",),
    ]
